### PR TITLE
fix: Hierarchy descendants return root siblings

### LINKED ISSUE #177: `Hierarchy::descendants` returns siblings of the root
```rust

    #[test]
    fn test_descendants_iter() {
        let mut hierarchy = Hierarchy::new();
        let root = NodeIndex::new(4);

        assert_eq!(hierarchy.child_count(root), 0);
        assert_eq!(hierarchy.parent(root), None);
        assert_eq!(hierarchy.first(root), None);
        assert_eq!(hierarchy.last(root), None);
        assert_eq!(hierarchy.next(root), None);
        assert_eq!(hierarchy.prev(root), None);

        // root
        //  |-> child0
        //  |-> child1
        //   -> child2
        let child0 = NodeIndex::new(0);
        let child1 = NodeIndex::new(1);
        let child2 = NodeIndex::new(2);
        hierarchy.push_front_child(child0, root).unwrap();
        hierarchy.push_child(child2, root).unwrap();
        hierarchy.insert_after(child1, child0).unwrap();

        // This returns the three siblings instead
        assert_eq!(
            hierarchy.descendants(child0).collect::<Vec<_>>(),
            vec![child0]
        );
    }
```

### PR DESCRIPTION
**Pull request by aborgna-q**
Closes #177

### CODE REVIEW

File: src/hierarchy.rs [hunk 1]
```diff
@@ -635,6 +636,8 @@ pub struct Descendants<'a> {
     /// For each region, we point to a child node that has not been visited yet.
     /// When a region is visited, we move to the next child node and queue its children region at the end of the queue.
     child_queue: VecDeque<NodeIndex>,
+    /// The root node we are iterating over.
+    root: NodeIndex,
 }
```
Comment (lmondada) [inline src/hierarchy.rs:641]: I let you be the judge of whether this is worth it, but in principle I'd much prefer something like:

```rust
enum NextStates {
    Root(NodeIndex),
    Children(VecDeque<NodeIndex>),
}

pub struct Descendants<'a> {
    /// The hierarchy this iterator is iterating over.
    layout: &'a Hierarchy,
    /// A queue of regions to visit.
    ///
    /// For each region, we point to a child node that has not been visited yet.
    /// When a region is visited, we move to the next child node and queue its children region at the end of the queue.
    next_states: NextStates,
}
```

It would make it clearer what the purpose of each field is, and will also make the `Default` implementation more sane.

**Review by lmondada — APPROVED** [review]
I suggest you turn `child_queue` and `root` into a sum type, but if you think it's more hassle than it's worth, then this is fine by me.

File: src/hierarchy.rs (hunk 1 above)
Comment (aborgna-q) [reply src/hierarchy.rs:641]: Sure, makes sense.
